### ISSUE TITLE
c99 fixes from Fedora

### ISSUE THREAD

**Issue by sharkcz** [ibm-s390-linux/libzfcphbaapi#1]
Please take a look at https://src.fedoraproject.org/rpms/libzfcphbaapi/blob/rawhide/f/libzfcphbaapi-c99.patch, I believe it's applicable to the 3.0 series as well.

https://fedoraproject.org/wiki/Changes/PortingToModernC
https://fedoraproject.org/wiki/Toolchain/PortingToModernC

Related: https://bugzilla.redhat.com/show_bug.cgi?id=2165019

PS: any plan to open this repo to public?

**Comment by fedorloshakov** [comment]
Hi, Dan! Thanks for noticing. I will take a look at it.

**Comment by sharkcz** [comment]
ping, as the project is public now :-)

**Comment by fedorloshakov** [comment]
Hi Dan, as we are still getting used to all processes for bringing fixes upstream, this will take some time. But we are working on it. Thanks for your patience.

**Comment by sharkcz** [comment]
thanks for the update
