### ISSUE TITLE
libHBAAPI2 and libHBAAPI2-devel

### ISSUE THREAD

**Issue by ngueorguiev** [ibm-s390-linux/libzfcphbaapi#2]
Hello @fedorloshakov , @steffen-maier 

Are there newer RPMs, e.g. 
libHBAAPI2-3.0.1-*.s390x.rpm
libHBAAPI2-devel-3.0.1-*.s390x.rpm

If yes, from were one could get them?
Thanks.

Kind regards,

**Comment by steffen-maier** [comment]
Hi Nikolay,

I would like to understand why you ask for libHBAAPI2 and why you ask for a packaged form (RPM).

We only provide the unpackaged source of libzfcphbaapi, which is an implementation of the HBA API standard. Our library can either be built as standalone library or as so-called vendor library. In the standalone form, applications link directly to libzfcphbaapi. In the vendor form, applications link to libHBAAPI2(-devel) and libHBAAPI2 dynamically loads a vendor library, which could be libzfcphbaapi; that way the actual implementation can be exchanged at runtime via a config file (/etc/hba.conf). 
(https://www.ibm.com/docs/en/linux-on-systems?topic=know-zfcp-hba-api
https://www.ibm.com/docs/en/linux-on-systems?topic=setup-installing-library)

LibHBAAPI2 is independent of libzfcphbaapi. AFAIK, libHBAAPI2 is just a wrapper library for the HBA API without any actual implementation of the HBA API. It's from the Storage Networking Industry Association ([SNIA](http://www.snia.org/)). While it might have (also) been hosted at http://open-fcoe.org/libHBAAPI in the past [I took that from the URL field in the RPM meta data], that domain does not seem functional to me any more (IIRC, that domain also provided a common implementation "libhbalinux" for FCoE and that implementation could plug into libHBAAPI2 as vendor library). For the SNIA wrapper library, our documentation (links in previous paragraph) points to https://hbaapi.sourceforge.net/.

SUSE builds libzfcphbaapi as vendor library and applications link against libHBAAPI2(-devel).
(https://www.ibm.com/docs/en/linux-on-systems?topic=sofc-zfcp-hba-api-2)
Building a new version of libzfcphbaapi should be possible without changing libHBAAPI2(-devel).

Regards,
Steffen

**Comment by ngueorguiev** [comment]
Hello Steffen,

The current build of `libzfcphbaapi` requires `libHBAAPI2-devel`. 
The `libzfcphbaapi` build succeeds with the older `libHBAAPI2-devel`. 

I was wondering if you know more about any requirements of a newer version of `libHBAAPI2-devel`. 

Thank you very much for the clarifications.

You might close this issue.

**Comment by steffen-maier** [comment]
discussion concluded, closing
